name: Run Python script every hour

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:      # Для ручного запуска

jobs:
  update_widget:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update Widget
        run: python widget.py